/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface LendingPoolParametersProviderInterface
  extends ethers.utils.Interface {
  functions: {
    "getFlashLoanFeesInBips()": FunctionFragment;
    "getMaxStableRateBorrowSizePercent()": FunctionFragment;
    "getRebalanceDownRateDelta()": FunctionFragment;
    "initialize(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getFlashLoanFeesInBips",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMaxStableRateBorrowSizePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRebalanceDownRateDelta",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "initialize", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "getFlashLoanFeesInBips",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMaxStableRateBorrowSizePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRebalanceDownRateDelta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;

  events: {};
}

export class LendingPoolParametersProvider extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: LendingPoolParametersProviderInterface;

  functions: {
    getFlashLoanFeesInBips(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    getMaxStableRateBorrowSizePercent(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getRebalanceDownRateDelta(overrides?: CallOverrides): Promise<[BigNumber]>;

    initialize(
      _addressesProvider: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getFlashLoanFeesInBips(
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  getMaxStableRateBorrowSizePercent(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getRebalanceDownRateDelta(overrides?: CallOverrides): Promise<BigNumber>;

  initialize(
    _addressesProvider: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getFlashLoanFeesInBips(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    getMaxStableRateBorrowSizePercent(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRebalanceDownRateDelta(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _addressesProvider: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getFlashLoanFeesInBips(overrides?: CallOverrides): Promise<BigNumber>;

    getMaxStableRateBorrowSizePercent(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRebalanceDownRateDelta(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _addressesProvider: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getFlashLoanFeesInBips(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMaxStableRateBorrowSizePercent(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRebalanceDownRateDelta(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _addressesProvider: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
